Add support for term meta data.
humanmade/WordPress-Importer pull request #18
Opened 2015-11-27 23:25 UTC by stephenharris

WordPress 4.4 adds term meta data, and [trac ticket 34602](https://core.trac.wordpress.org/ticket/34062), adds term meta data to the WXR export file. Although that ticket is still open, and is unlikely to be in 4.4, this PR adds support for importing term meta data, following the schema set out in that ticket.

2016-01-21 07:38 UTC, anhskohbo commented
+1

2016-02-12 03:28 UTC, rmccue commented
Thanks for the PR, and apologies for the delayed response! Going to hold off on this until the core one is merged. :)

2016-04-18 03:37 UTC, livinglab commented
https://core.trac.wordpress.org/changeset/37240

2016-04-18 03:38 UTC, boonebgorges commented
https://core.trac.wordpress.org/changeset/37240

2016-05-23 17:42 UTC, swissspidy commented
Pending a final review this looks good to me.

2016-08-17 16:54 UTC, shivapoudel commented
@rmccue Isn't the core one is merged till date :shipit:

2016-11-18 20:40 UTC, JJJ commented
This still looks good!

2017-03-08 02:26 UTC, rmccue requested changes

2017-03-08 02:26 UTC, rmccue commented on class-wxr-importer.php
> +			if ( $key ) {
This should be `if ( ! $key ) { continue' }`

2017-03-08 02:26 UTC, rmccue commented on class-wxr-importer.php
> +			$key = apply_filters( 'import_term_meta_key', $meta_item['key'], $term_id, $term );
Is this an existing filter in the v1 importer? If not, should be `wxr_importer.process_term_meta.key`. Needs documentation too.

If it's not an existing filter, not sure what it offers over the above `wxr_importer.pre_process.term_meta` filter.

2017-03-08 02:26 UTC, rmccue commented on class-wxr-importer.php
> +			$meta_item = apply_filters( 'wxr_importer.pre_process.term_meta', $meta_item, $term_id );
Should pass `$term` here too.

2017-03-08 02:26 UTC, rmccue commented on class-wxr-importer.php
> +				do_action( 'import_term_meta', $term_id, $key, $value );
Is this also an existing action?

2017-03-08 02:26 UTC, rmccue commented on class-wxr-importer.php
> +			} else if ( $child->tagName == 'wp:termmeta' ) {
`else if` -> `elseif`

2017-03-08 02:26 UTC, rmccue commented
@stephenharris Sorry for the long delay here :( Submitted a review; if you don't have time to fix this up, I can do so for you.

2017-03-08 03:29 UTC, JJJ commented on class-wxr-importer.php
> +			} else if ( $child->tagName == 'wp:termmeta' ) {
Agree.

2017-03-08 03:29 UTC, JJJ commented on class-wxr-importer.php
> +			$meta_item = apply_filters( 'wxr_importer.pre_process.term_meta', $meta_item, $term_id );
Agree.

2017-03-08 03:30 UTC, JJJ commented on class-wxr-importer.php
> +			$key = apply_filters( 'import_term_meta_key', $meta_item['key'], $term_id, $term );
Agree.

2017-03-08 03:31 UTC, JJJ commented on class-wxr-importer.php
> +			if ( $key ) {
Good catch.

2017-03-08 21:28 UTC, stephenharris commented on class-wxr-importer.php
> +			$meta_item = apply_filters( 'wxr_importer.pre_process.term_meta', $meta_item, $term_id );
Happy too, but I wrote this to be consistent with post meta, so we ought to change https://github.com/humanmade/WordPress-Importer/blob/master/class-wxr-importer.php#L1146 too.

(Is backwards compatibility a concern here? If not, we could just replace `$term_id` with `$term`, and similarly for posts).

2017-03-08 21:30 UTC, stephenharris commented on class-wxr-importer.php
> +			$key = apply_filters( 'import_term_meta_key', $meta_item['key'], $term_id, $term );
The name is adapted from https://github.com/humanmade/WordPress-Importer/blob/master/class-wxr-importer.php#L1151

In view of that, do we still want the name changed? What about post meta?

2017-03-08 21:32 UTC, stephenharris commented on class-wxr-importer.php
> +				do_action( 'import_term_meta', $term_id, $key, $value );
See earlier comments :)

2017-03-08 22:14 UTC, stephenharris commented on class-wxr-importer.php
> +			$key = apply_filters( 'import_term_meta_key', $meta_item['key'], $term_id, $term );
Actually, these hooks are in the v1 importer - but they were added after this PR was opened.

2017-03-08 22:30 UTC, stephenharris commented
I clearly messed up re-basing this. I'm going to squash my commits into one and forcibly push it onto my feature branch...

2017-03-08 22:40 UTC, stephenharris commented
Decided to open a new PR for this: #106 

Sorry for the noise all.

2017-03-08 22:40 UTC, closed without merging

2017-03-08 23:32 UTC, rmccue commented
In future, please don't rebase, just merge `master` into your branch regularly :)